config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  use_doorkeeper
  mount_griddler

  concern :acts_as_chartable do
    namespace :charts do
      resources :productions, only: :index
      resources :cpues, only: :index
      resources :fuel_utilizations, only: :index
      resources :catch_compositions, only: :index
      resources :bait_efficiencies, only: :index
    end
  end



  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do




    devise_for :users,
      path_prefix: 'session',
      controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    devise_for :admins,
      path_prefix: 'session',
      controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'admins/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    namespace :panel do
      resources :users do
        member do
          post :add_role
          delete :delete_role
        end
      end
      resources :admins do
        member do
          post :add_role
          delete :delete_role
          put :set_approved
        end
      end
      resources :roles, :only=>[:index, :create, :destroy]
    end

    namespace :supervisor do
      resources :surveys
      resources :logbooks
      resources :admins
      resources :dashboard
    end

    namespace :staff do
      resources :dashboard
    end

    resources :catches
    resources :desas do
      resources :surveys
    end
    resources :fisheries do
      concerns :acts_as_chartable
      resources :companies, only: [:create, :new]
      resources :gears, only: [:create, :new]
      resources :fishes, only: [:create, :new]
      resources :offices, only: [:create, :new]
      member do
        get :report
        post :add_target_fish
        delete :delete_target_fish
        post :add_bait_fish
        delete :delete_bait_fish
        post :add_used_gear
        delete :delete_used_gear
        post :add_member_company
        post :create_member_company
        get :new_member_company
        delete :delete_member_company
        post :add_member_office
        delete :delete_member_office
      end
    end
    post    "/fisheries/:fishery_id/memberships/gears"     => "memberships/gears#create",  as: "fishery_add_gear"
    delete  "/fisheries/:fishery_id/memberships/gears/:id" => "memberships/gears#destroy", as: "fishery_remove_gear"
    post    "/fisheries/:fishery_id/memberships/vessels"     => "memberships/vessels#create",  as: "fishery_add_vessel"
    delete  "/fisheries/:fishery_id/memberships/vessels/:id" => "memberships/vessels#destroy", as: "fishery_remove_vessel"
    post    "/fisheries/:fishery_id/memberships/fishes"     => "memberships/fishes#create",  as: "fishery_add_fish"
    delete  "/fisheries/:fishery_id/memberships/fishes/:id" => "memberships/fishes#destroy", as: "fishery_remove_fish"
    resources :fishes do
      collection do
        post :import
        get :autocomplete
      end
    end
    resources :gears
    resources :landings
    resources :offices do
      namespace :memberships do
        #resources :admins, only: [:create, :destroy]
      end
      member do
        post :add_admin
        delete :delete_admin
      end
    end
    post "/offices/:office_id/memberships/admins" => "memberships/admins#create", as: "office_add_admin"
    delete "/offices/:office_id/memberships/admins/:id" => "memberships/admins#destroy", as: "office_remove_admin"
    resources :surveys do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :audits, except: [:edit] do
      resources :pending_vessels, only: [:new, :create]
    end
    resources :engines
    resources :ports do
      concerns :acts_as_chartable
    end
    resources :wpps do
      concerns :acts_as_chartable
    end
    resources :graticules
    resources :vessel_types
    resources :districts
    resources :provinces
    resources :logbooks do
      put :approve, on: :member
      put :pend, on: :member
      put :reject, on: :member
    end
    resources :logged_days
    resources :excel_files
    resources :activities

    resources :responders

    resources :tests
    resources :drafts, only: [:update,:destroy]

    resources :vessels do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :audits, except: [:edit]
      collection do
        get :generate_stickers
      end
    end
    resources :pending_vessels do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :vessel_imports do
      collection do
        get :template
      end
    end
    resources :unloading_imports do
      collection do
        get :template
      end
    end
    resources :bait_loading_imports do
      collection do
        get :template
      end
    end

    resources :unloadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :unloading_catches, only: [:create,:update,:destroy]
    resources :carrier_loadings
    resources :size_classes

    resources :companies do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :vessels
      resources :audits, except: [:edit]
      member do
        get 'crop' => 'companies#crop', :as => :crop
        get :report
        post :add_vessel
        delete :delete_vessel
        get 'report'
        get :average_catch_composition
        get :current_catch_composition
        get :current_monthly_production
        get :average_monthly_production
        get :current_monthly_cpue
        get :average_monthly_cpue
        get :current_fuel_utilization
        post :add_user
        delete :delete_user
      end
    end
    post    "/companies/:company_id/memberships/users"     => "memberships/users#create",  as: "company_add_user"
    delete  "/companies/:company_id/memberships/users/:id" => "memberships/users#destroy", as: "company_remove_user"

    resources :bait_loadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :baits

    resources :documents

    resources :protocols

    resources :users, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get 'welcome' => 'users#welcome', :as => :welcome
        get :report
        get :crop
      end
    end
    resources :admins, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get :welcome
        get :crop
      end
    end

    resources :importers, only: [:index]

    namespace :review do
      resources :unloadings,    only: [:update]
      resources :bait_loadings, only: [:update]
    end

    namespace :api, defaults: {format: 'json'} do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
        # resources :users
        # resources :admins
        # resources :logbooks
        # resources :surveys
        resources :fisheries
        # resources :desas, path: :landing_sites
        # resources :districts
        # resources :provinces
        # resources :engines
        # resources :gears
        resources :fishes
        resources :vessels, only: [:index]
        resources :unloadings, only: [:index]
      end
    end




  #  get 'home/index'
#    get 'home/upload_data'
#    get 'home/import'
    get '/reports' => 'home#reports'
    get '/user_profile' => 'home#user_profile'
    get '/fishery_profile' => 'home#fishery_profile'
    get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"


    match '/multipart_import' => 'home#multipart_import', via: [:get, :post]
    post '/import_mail' => 'home#import_mail'

    post 'home/process_upload_data'

    get "/home/*page"  => "home#show",          as: :page

    #authenticate :admin, lambda { |a| a.admin? } do

    #end
    authenticated :admin do
      root :to => "home#index", as: :admin_root
      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :user do
      root to: 'users#home', as: :user_root
    end
    # handles /valid-locale
    get '/:locale' => 'home#index'
    root to: 'home#index'
    # handles /valid-locale/fake-path
    #match '*path', to: redirect { |params, request| "/#{params[:locale]}" }

  end





  # handles /bad-locale|anything/valid-path
  match '/*locale/*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get

  # handles /anything|valid-path-but-no-locale
  match '/*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get

  # handles /
  #root to: redirect("/#{I18n.default_locale}")
  match '', to: redirect("/#{I18n.default_locale}"), via: :get



end

app/models/office.rb
# == Schema Information
#
# Table name: offices
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  district_id :integer
#

class Office < ApplicationRecord

  has_paper_trail

  # attr_accessible :name, :district_id
  scope :default, -> { order('offices.name ASC') }

  has_many :admins
  belongs_to :district
  has_one :province, through: :district

  has_and_belongs_to_many :member_fisheries, class_name: "Fishery"

  attr_accessor :fishery_id

  validates :name,
  	presence: true

  def supervisors
    Rails.cache.fetch([self, "supvervisors"], expires_in: 5.minutes) do
      Admin.joins(:roles).where(roles: {name: ["supervisor", "leader", "administrator"]}).where(office_id: self.id)
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  load_and_authorize_resource

  #before_action :set_office, only: [:show, :edit, :update, :destroy, :add_admin]
  respond_to :html
  respond_to :xml, :json, :csv, :xls, :js, :except => [ :edit, :new, :update, :create ]

  def index
    @offices = @offices.default.page(params[:page])
    respond_to do |format|
      format.html
      format.js
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"offices-#{Date.current}.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @office = Office.new(office_params)
    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: t('.notice') }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @office = Office.find(params[:id])
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  def crop
    @office = Office.find(params[:id])
    render :crop
  end

  def add_admin
    admin = Admin.find_by_email params[:get_admin]
    if admin
      if @office.admins.include?(admin)
        flash[:alert]= I18n.t("offices.admins.exists")
      else
       @office.admins.push admin
       flash[:success]= I18n.t("offices.admins.created")
      end
      redisplay_admins
    else
      email = params[:get_admin]
      name  = email[0,email.index('@')]
      Admin.invite!({ email: email, name: name, office_id: @office.id, approved: true }, current_admin)
      flash[:success]= I18n.t("offices.admins.invited", office: @office.name )
      redisplay_admins
    end

  end

  def delete_admin
    admin = Admin.find params[:admin]
    admin.update_attribute( :office_id, "")
    flash[:success]= I18n.t("offices.admins.removed")
    redisplay_admins
  end

  private

  def set_office
    @office = Office.find(params[:id])
  end

  def office_params
    params.require(:office).permit(
      :name,
      :district_id
      )
  end

  def after_save_path_for(resource)
    if params[:office][:avatar].present?
      crop_office_path(resource)
    elsif params[:office][:fishery_id].present?
      fishery = Fishery.find( params[:office][:fishery_id] )
      fishery.member_offices.push resource
      fishery_path(params[:office][:fishery_id])
    else
      root_path
      #company_path(resource)
    end
  end

  def redisplay_admins
    respond_to do |format|
      format.html { redirect_to @office }
      format.js { render :redisplay_admins }
    end
  end

end

app/views/offices/_admin_list.html.erb
<div id="AdminList">
  <br />
  <ul class="list-unstyled">
    <% @office.admins.each do |admin| %>
      <li>
        <% if admin.pending_invitation? %>
          <i><%= admin.email %> <small>(invitation pending)</small> </i>
        <% else %>
          <b><%= link_to admin.name, admin %></b>
        <% end %>
        <% if can? :update, @office %>
          <%= link_to remove_icon, delete_admin_office_path(@office, admin: admin.id), method: :delete, confirm: 'Are you sure?', remote: true %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/offices/_admin_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Staff</h3>
  </div>
  <div class="panel-body">
    <% if ( can? :create, Admin ) && ( can? :update, @office ) %>
      <%= form_tag office_add_admin_path(@office), class: "form", method: :post, remote: true do %>
        <%= label_tag 'admin[email]', 'Add a team member', class: 'hidden-xs' %>
        <div class="input-group">
          <%= text_field :admin, :email, class: "form-control", placeholder: "Add a team member...", autocomplete: "off", data: { autocomplete_source: Admin.order(:email).map(&:email) } %>
          <span class="input-group-btn">
            <%= button_tag add_icon, class: "btn btn-success", id: 'add_admin', title: 'Add Admin' %>
          </span>
        </div>
      <% end %>
    <% end %>
    <%= render partial: 'admin_list' %>
  </div>
</div>

app/views/offices/_form.html.erb
<%= simple_form_for @office, html: {class: 'form form-horizontal'} do |f| %>
  
  <div class="row">

    <div class="col-xs-12 col-md-6 col-md-offset-3">
  
      <%= f.input :fishery_id, as: :hidden %>

      <%= f.input :name %>

      <%= f.association :district %>

    </div>

  </div>
    

  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3 form-actions">

      <%= content_tag :button, type: :submit, class: 'btn btn-primary pull-right', style:"margin-left:20px" do %>
        Save
      <% end %>


      <% if !f.object.new_record? %>
        <%= link_to "Cancel", @office, :class=>"btn pull-right" %>

      <% else %>
        <%= link_to "Cancel", offices_path, :class=>"btn pull-right" %>
      <% end %> 

    </div>
  </div>
<% end %>

app/views/offices/_office_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Details</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt><%= Office.human_attribute_name(:name) %></dt>
      <dd><%= @office.name %></dd>
      <dt><%= Office.human_attribute_name(:district_id) %></dt>
      <dd><%= @office.district.try(:name) %></dd>
    </dl>
  </div>
</div>

app/views/offices/index.csv.erb
<%- headers = ["id", "name"] -%>

<%= CSV.generate_line headers %>
<%- @offices.each do |office| -%>
<%= CSV.generate_line(
	[
		office.id,
		office.name
	]
) -%>
<%- end -%>

app/views/offices/index.html.erb
<% title t ".title" %>

<%= link_to new_office_path, class: "btn btn-mini btn-default", title: "Create new office", alt: "New office" do %>
  <%= icon fa_new, "NEW" %>
<% end %>

<%= render partial: "shared/api_links", locals: {json: true, xml: true} %>


<table  class="table table-striped table-condensed datatable">
  <thead>
    <tr>
      <th></th>
      <th><%= Company.human_attribute_name(:name) %></th>
      <th><%= Company.human_attribute_name(:district) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= link_to show_icon, office %> </td>
        <td><%= link_to office.name, office %></td>
        <td><%= office.district.try(:name) %></td>
        <td>
          <% if can? :update, office %>
            <%= link_to edit_icon, edit_office_path(office) %>
          <% end %>
          <% if can? :destroy, office %>
            <%= link_to destroy_icon, office, method: :delete, data: { confirm: "This will permanently delete this record and all associated records.\nAre you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

app/views/offices/redisplay_admins.js.erb
$('#AdminList').replaceWith("<%= escape_javascript(render :partial=>'admin_list') %>");
$(".flash-container").html("<%= escape_javascript(render partial: 'shared/flash_messages') %>");
$(".alert").delay(3000).fadeOut('slow');

app/views/offices/show.html.erb
<% title t ".title" %>

<div class="row">
  <div class="col-xs-12 col-md-8">
    <div class="row">
      <div class="col-xs-12">
        <%= render partial: "office_panel" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <%= render partial: 'shared/audit_table', locals: { parent: @office } %>
      </div>
    </div>
  </div>
  <div id="member_panel" class="col-xs-12 col-md-4">
    <%= render partial: "admin_panel" %>
  </div>
</div>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>