config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  use_doorkeeper
  mount_griddler

  concern :acts_as_chartable do
    namespace :charts do
      resources :productions, only: :index
      resources :cpues, only: :index
      resources :fuel_utilizations, only: :index
      resources :catch_compositions, only: :index
      resources :bait_efficiencies, only: :index
    end
  end



  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do




    devise_for :users,
      path_prefix: 'session',
      controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    devise_for :admins,
      path_prefix: 'session',
      controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'admins/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    namespace :panel do
      resources :users do
        member do
          post :add_role
          delete :delete_role
        end
      end
      resources :admins do
        member do
          post :add_role
          delete :delete_role
          put :set_approved
        end
      end
      resources :roles, :only=>[:index, :create, :destroy]
    end

    namespace :supervisor do
      resources :surveys
      resources :logbooks
      resources :admins
      resources :dashboard
    end

    namespace :staff do
      resources :dashboard
    end

    resources :catches
    resources :desas do
      resources :surveys
    end
    resources :fisheries do
      concerns :acts_as_chartable
      resources :companies, only: [:create, :new]
      resources :gears, only: [:create, :new]
      resources :fishes, only: [:create, :new]
      resources :offices, only: [:create, :new]
      member do
        get :report
        post :add_target_fish
        delete :delete_target_fish
        post :add_bait_fish
        delete :delete_bait_fish
        post :add_used_gear
        delete :delete_used_gear
        post :add_member_company
        post :create_member_company
        get :new_member_company
        delete :delete_member_company
        post :add_member_office
        delete :delete_member_office
      end
    end
    post    "/fisheries/:fishery_id/memberships/gears"     => "memberships/gears#create",  as: "fishery_add_gear"
    delete  "/fisheries/:fishery_id/memberships/gears/:id" => "memberships/gears#destroy", as: "fishery_remove_gear"
    post    "/fisheries/:fishery_id/memberships/vessels"     => "memberships/vessels#create",  as: "fishery_add_vessel"
    delete  "/fisheries/:fishery_id/memberships/vessels/:id" => "memberships/vessels#destroy", as: "fishery_remove_vessel"
    post    "/fisheries/:fishery_id/memberships/fishes"     => "memberships/fishes#create",  as: "fishery_add_fish"
    delete  "/fisheries/:fishery_id/memberships/fishes/:id" => "memberships/fishes#destroy", as: "fishery_remove_fish"
    resources :fishes do
      collection do
        post :import
        get :autocomplete
      end
    end
    resources :gears
    resources :landings
    resources :offices do
      namespace :memberships do
        #resources :admins, only: [:create, :destroy]
      end
      member do
        post :add_admin
        delete :delete_admin
      end
    end
    post "/offices/:office_id/memberships/admins" => "memberships/admins#create", as: "office_add_admin"
    delete "/offices/:office_id/memberships/admins/:id" => "memberships/admins#destroy", as: "office_remove_admin"
    resources :surveys do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :audits, except: [:edit] do
      resources :pending_vessels, only: [:new, :create]
    end
    resources :engines
    resources :ports do
      concerns :acts_as_chartable
    end
    resources :wpps do
      concerns :acts_as_chartable
    end
    resources :graticules
    resources :vessel_types
    resources :districts
    resources :provinces
    resources :logbooks do
      put :approve, on: :member
      put :pend, on: :member
      put :reject, on: :member
    end
    resources :logged_days
    resources :excel_files
    resources :activities

    resources :responders

    resources :tests
    resources :drafts, only: [:update,:destroy]

    resources :vessels do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :audits, except: [:edit]
      collection do
        get :generate_stickers
      end
    end
    resources :pending_vessels do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :vessel_imports do
      collection do
        get :template
      end
    end
    resources :unloading_imports do
      collection do
        get :template
      end
    end
    resources :bait_loading_imports do
      collection do
        get :template
      end
    end

    resources :unloadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :unloading_catches, only: [:create,:update,:destroy]
    resources :carrier_loadings
    resources :size_classes

    resources :companies do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :vessels
      resources :audits, except: [:edit]
      member do
        get 'crop' => 'companies#crop', :as => :crop
        get :report
        post :add_vessel
        delete :delete_vessel
        get 'report'
        get :average_catch_composition
        get :current_catch_composition
        get :current_monthly_production
        get :average_monthly_production
        get :current_monthly_cpue
        get :average_monthly_cpue
        get :current_fuel_utilization
        post :add_user
        delete :delete_user
      end
    end
    post    "/companies/:company_id/memberships/users"     => "memberships/users#create",  as: "company_add_user"
    delete  "/companies/:company_id/memberships/users/:id" => "memberships/users#destroy", as: "company_remove_user"

    resources :bait_loadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :baits

    resources :documents

    resources :protocols

    resources :users, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get 'welcome' => 'users#welcome', :as => :welcome
        get :report
        get :crop
      end
    end
    resources :admins, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get :welcome
        get :crop
      end
    end

    resources :importers, only: [:index]

    namespace :review do
      resources :unloadings,    only: [:update]
      resources :bait_loadings, only: [:update]
    end

    namespace :api, defaults: {format: 'json'} do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
        # resources :users
        # resources :admins
        # resources :logbooks
        # resources :surveys
        resources :fisheries
        # resources :desas, path: :landing_sites
        # resources :districts
        # resources :provinces
        # resources :engines
        # resources :gears
        resources :fishes
        resources :vessels, only: [:index]
        resources :unloadings, only: [:index]
      end
    end




  #  get 'home/index'
#    get 'home/upload_data'
#    get 'home/import'
    get '/reports' => 'home#reports'
    get '/user_profile' => 'home#user_profile'
    get '/fishery_profile' => 'home#fishery_profile'
    get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"


    match '/multipart_import' => 'home#multipart_import', via: [:get, :post]
    post '/import_mail' => 'home#import_mail'

    post 'home/process_upload_data'

    get "/home/*page"  => "home#show",          as: :page

    #authenticate :admin, lambda { |a| a.admin? } do

    #end
    authenticated :admin do
      root :to => "home#index", as: :admin_root
      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :user do
      root to: 'users#home', as: :user_root
    end
    # handles /valid-locale
    get '/:locale' => 'home#index'
    root to: 'home#index'
    # handles /valid-locale/fake-path
    #match '*path', to: redirect { |params, request| "/#{params[:locale]}" }

  end





  # handles /bad-locale|anything/valid-path
  match '/*locale/*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get

  # handles /anything|valid-path-but-no-locale
  match '/*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get

  # handles /
  #root to: redirect("/#{I18n.default_locale}")
  match '', to: redirect("/#{I18n.default_locale}"), via: :get



end

app/controllers/panel/admins_controller.rb
class Panel::AdminsController < ApplicationController
  before_filter :load_admin, :except=>[:index]

  
  def index
   
    if params[:approved] == "false"
      @admins = Admin.find_all_by_approved(false)
    else
      @admins = Admin.all
    end
  end

  def show
  end

  def get_role
    role.try(:name)
  end


  def add_role
    role = Role.find_by_name params[:get_role]
    if role
      if @admin.roles.include?(role)
        flash[:error]= I18n.t("panel.roles.exists")
      else
       @admin.roles.push role
       flash[:success]= I18n.t("panel.roles.exists")
      end 
    end
    redisplay_roles
  end

  def delete_role
    @admin.roles.delete(Role.find params[:role])
    flash[:success]= I18n.t("panel.roles.exists")
    redisplay_roles
  end

  def set_approved
    @admin = Admin.find(params[:id])
    @admin.update_column :approved, params[:approved]
    if @admin.approved?
      flash[:success] = "Approved"
      UserMailer.new_admin_approved(@admin.id).deliver_later
    else
      flash[:error] = "Not Approved"
    end
    render nothing: true
  end

  private

  def load_admin
    @admin = Admin.find params[:id]
  end

  def redisplay_roles
    respond_to do |format|
      format.html { redirect_to [:panel, @admin] }
      format.js { render :redisplay_roles }
    end
  end

  
end

app/controllers/panel/roles_controller.rb
class Panel::RolesController < ApplicationController

  def index
    @roles = Role.all
    @new_role = Role.new
  end

  def create
    Role.create role_params
    redisplay_roles
  end

  def destroy
    Role.find(params[:id]).destroy
    redisplay_roles
  end

  private

  def redisplay_roles
    respond_to do |format|
      format.html { redirect_to panel_roles_path }
      format.js {
        @roles = Role.all
        render :redisplay_roles
      }
    end
  end

  private
  def role_params
    params.require(:user).permit( :name)
  end
  
end

app/controllers/panel/users_controller.rb
class Panel::UsersController < ApplicationController
  before_filter :load_user, :except=>[:index]
  def index
    @users = User.all
  end

  def show
  end

  def get_role
  	role.try(:name)
  end

  def add_role
    role = Role.find_by_name params[:get_role]
    if role
      if @user.roles.include?(role)
        flash[:error]= I18n.t("panel.roles.exists")
      else
       @user.roles.push role
       flash[:success]= I18n.t("panel.roles.exists")
      end 
    end
    redisplay_roles
  end

  def delete_role
    @user.roles.delete(Role.find params[:role])
    flash[:success]= I18n.t("panel.roles.exists")
    redisplay_roles
  end

  private

  def load_user
    @user = User.find params[:id]
  end

  def redisplay_roles
    respond_to do |format|
      format.html { redirect_to [:panel, @user] }
      format.js { render :redisplay_roles }
    end
  end
end

app/helpers/panel/admins_helper.rb
module Panel::AdminsHelper
end

app/helpers/panel/roles_helper.rb
module Panel::RolesHelper
end

app/helpers/panel/users_helper.rb
module Panel::UsersHelper
end

app/views/panel/admins/_admin_item.html.erb
<% for admin in @admins %>
  <tr>
    <td><%= image_tag(admin.avatar_url(:thumb), width: "30px", height: "30px") %></td>
    <td><%= link_to admin.name, [:panel, admin] %></td>
    <td><%= admin.office.try(:name) %></td>
    <td><%= admin.district.try(:name) %></td>
    <td><%= admin.province.try(:name) %></td>
    <td>
      <% if can? :update, admin %> 
        
          <%= check_box_tag :approved, 
            admin.id, 
            admin.approved?, 
            class: 'toggle-switch approve-toggle', 
            data: { 
              href: set_approved_panel_admin_path(admin),
              size: 'mini',
              'on-color' => 'success',
              'off-color' => 'danger',
              'on-text' => "#{ icon 'check' }",
              'off-text' => "#{ icon 'remove' }"
            } %>

      <% end %>
    </td>
    <td>
      <%= link_to show_icon, [:panel, admin] %>
    </td>
  </tr>
<% end %>

app/views/panel/admins/_role_list.html.erb
<div id="RoleList">
  <ul>
    <% @admin.roles.each do |role| %>
      <li>
				<%= role.name %>
        <% if can? :update, Role %>
    		  <%= link_to remove_icon, delete_role_panel_admin_path(@admin, :role=>role.id), method: :delete, confirm: 'Are you sure?', remote: true %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/panel/admins/index.html.erb
<% title "Admins" %>

<div class="btn-group pull-right">
  <%= link_to "All", { :action => "index" }, class: "btn btn-mini", remote: true %>
  <%= link_to "Awaiting approval", { :action => "index", :approved => "false" }, class: "btn btn-mini", remote: true %>
</div>

<br />
<br />

<table class="table table-striped table-condensed datatable">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Office</th>
      <th>District</th>
      <th>Province</th>
      <th>Approved</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="admins_body">
    <%= render partial: "panel/admins/admin_item" %>
  </tbody>
 </table>

app/views/panel/admins/index.js.erb
$('#admins_body').html('<%= escape_javascript(render partial: "panel/admins/admin_item") %>');
$('.switch')['bootstrapSwitch']();

app/views/panel/admins/redisplay_roles.js.erb
$('#RoleList').replaceWith("<%= escape_javascript(render :partial=>'role_list') %>");
$(".flash-container").html("<%= escape_javascript(render partial: 'shared/flash_messages') %>");
$(".alert").delay(3000).fadeOut('slow');

app/views/panel/admins/show.html.erb
<% title @admin.name %>

<%= @admin.email %>
<div id="flash"></div>
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Roles</h3>
      </div>
      <div class="panel-body">

          <% if can? :update, Role %>
            <%= form_tag [:add_role, :panel, @admin], class: "form", :remote=>true do %>
              <div class="input-group">

                <%= text_field_tag :get_role, "", class: "form-control", placeholder: "Assign a role...", autocomplete: "off", data: { autocomplete_source: Role.order(:name).map(&:name) } %>
                <div class="input-group-btn">
                  <%= button_tag add_icon, class: "btn btn-success" %>
                </div>
              </div>
            <% end %>
          <% end %>

        <%= render :partial=>'role_list' %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Return to Admin List', [:panel, Admin] %>