config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  use_doorkeeper
  mount_griddler

  concern :acts_as_chartable do
    namespace :charts do
      resources :productions, only: :index
      resources :cpues, only: :index
      resources :fuel_utilizations, only: :index
      resources :catch_compositions, only: :index
      resources :bait_efficiencies, only: :index
    end
  end



  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do




    devise_for :users,
      path_prefix: 'session',
      controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    devise_for :admins,
      path_prefix: 'session',
      controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'admins/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    namespace :panel do
      resources :users do
        member do
          post :add_role
          delete :delete_role
        end
      end
      resources :admins do
        member do
          post :add_role
          delete :delete_role
          put :set_approved
        end
      end
      resources :roles, :only=>[:index, :create, :destroy]
    end

    namespace :supervisor do
      resources :surveys
      resources :logbooks
      resources :admins
      resources :dashboard
    end

    namespace :staff do
      resources :dashboard
    end

    resources :catches
    resources :desas do
      resources :surveys
    end
    resources :fisheries do
      concerns :acts_as_chartable
      resources :companies, only: [:create, :new]
      resources :gears, only: [:create, :new]
      resources :fishes, only: [:create, :new]
      resources :offices, only: [:create, :new]
      member do
        get :report
        post :add_target_fish
        delete :delete_target_fish
        post :add_bait_fish
        delete :delete_bait_fish
        post :add_used_gear
        delete :delete_used_gear
        post :add_member_company
        post :create_member_company
        get :new_member_company
        delete :delete_member_company
        post :add_member_office
        delete :delete_member_office
      end
    end
    post    "/fisheries/:fishery_id/memberships/gears"     => "memberships/gears#create",  as: "fishery_add_gear"
    delete  "/fisheries/:fishery_id/memberships/gears/:id" => "memberships/gears#destroy", as: "fishery_remove_gear"
    post    "/fisheries/:fishery_id/memberships/vessels"     => "memberships/vessels#create",  as: "fishery_add_vessel"
    delete  "/fisheries/:fishery_id/memberships/vessels/:id" => "memberships/vessels#destroy", as: "fishery_remove_vessel"
    post    "/fisheries/:fishery_id/memberships/fishes"     => "memberships/fishes#create",  as: "fishery_add_fish"
    delete  "/fisheries/:fishery_id/memberships/fishes/:id" => "memberships/fishes#destroy", as: "fishery_remove_fish"
    resources :fishes do
      collection do
        post :import
        get :autocomplete
      end
    end
    resources :gears
    resources :landings
    resources :offices do
      namespace :memberships do
        #resources :admins, only: [:create, :destroy]
      end
      member do
        post :add_admin
        delete :delete_admin
      end
    end
    post "/offices/:office_id/memberships/admins" => "memberships/admins#create", as: "office_add_admin"
    delete "/offices/:office_id/memberships/admins/:id" => "memberships/admins#destroy", as: "office_remove_admin"
    resources :surveys do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :audits, except: [:edit] do
      resources :pending_vessels, only: [:new, :create]
    end
    resources :engines
    resources :ports do
      concerns :acts_as_chartable
    end
    resources :wpps do
      concerns :acts_as_chartable
    end
    resources :graticules
    resources :vessel_types
    resources :districts
    resources :provinces
    resources :logbooks do
      put :approve, on: :member
      put :pend, on: :member
      put :reject, on: :member
    end
    resources :logged_days
    resources :excel_files
    resources :activities

    resources :responders

    resources :tests
    resources :drafts, only: [:update,:destroy]

    resources :vessels do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :audits, except: [:edit]
      collection do
        get :generate_stickers
      end
    end
    resources :pending_vessels do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :vessel_imports do
      collection do
        get :template
      end
    end
    resources :unloading_imports do
      collection do
        get :template
      end
    end
    resources :bait_loading_imports do
      collection do
        get :template
      end
    end

    resources :unloadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :unloading_catches, only: [:create,:update,:destroy]
    resources :carrier_loadings
    resources :size_classes

    resources :companies do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :vessels
      resources :audits, except: [:edit]
      member do
        get 'crop' => 'companies#crop', :as => :crop
        get :report
        post :add_vessel
        delete :delete_vessel
        get 'report'
        get :average_catch_composition
        get :current_catch_composition
        get :current_monthly_production
        get :average_monthly_production
        get :current_monthly_cpue
        get :average_monthly_cpue
        get :current_fuel_utilization
        post :add_user
        delete :delete_user
      end
    end
    post    "/companies/:company_id/memberships/users"     => "memberships/users#create",  as: "company_add_user"
    delete  "/companies/:company_id/memberships/users/:id" => "memberships/users#destroy", as: "company_remove_user"

    resources :bait_loadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :baits

    resources :documents

    resources :protocols

    resources :users, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get 'welcome' => 'users#welcome', :as => :welcome
        get :report
        get :crop
      end
    end
    resources :admins, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get :welcome
        get :crop
      end
    end

    resources :importers, only: [:index]

    namespace :review do
      resources :unloadings,    only: [:update]
      resources :bait_loadings, only: [:update]
    end

    namespace :api, defaults: {format: 'json'} do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
        # resources :users
        # resources :admins
        # resources :logbooks
        # resources :surveys
        resources :fisheries
        # resources :desas, path: :landing_sites
        # resources :districts
        # resources :provinces
        # resources :engines
        # resources :gears
        resources :fishes
        resources :vessels, only: [:index]
        resources :unloadings, only: [:index]
      end
    end




  #  get 'home/index'
#    get 'home/upload_data'
#    get 'home/import'
    get '/reports' => 'home#reports'
    get '/user_profile' => 'home#user_profile'
    get '/fishery_profile' => 'home#fishery_profile'
    get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"


    match '/multipart_import' => 'home#multipart_import', via: [:get, :post]
    post '/import_mail' => 'home#import_mail'

    post 'home/process_upload_data'

    get "/home/*page"  => "home#show",          as: :page

    #authenticate :admin, lambda { |a| a.admin? } do

    #end
    authenticated :admin do
      root :to => "home#index", as: :admin_root
      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :user do
      root to: 'users#home', as: :user_root
    end
    # handles /valid-locale
    get '/:locale' => 'home#index'
    root to: 'home#index'
    # handles /valid-locale/fake-path
    #match '*path', to: redirect { |params, request| "/#{params[:locale]}" }

  end





  # handles /bad-locale|anything/valid-path
  match '/*locale/*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get

  # handles /anything|valid-path-but-no-locale
  match '/*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get

  # handles /
  #root to: redirect("/#{I18n.default_locale}")
  match '', to: redirect("/#{I18n.default_locale}"), via: :get



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'mail'
  authorize_resource :class => false
  skip_before_filter :authenticate!, :verify_authenticity_token, :only => [:import_mail, :multipart_import], raise: false

  skip_authorize_resource :only => :multipart_import

  def show
    if valid_page?
      initialize_select_company_page  if params[:page] == 'select_company'
      initialize_select_vessel_page   if params[:page] == 'select_vessel'
      render template: "home/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end




  def index
    @activities = Activity.includes(:ownable, :trackable).page(params[:page]).per(15)
  end

  def reports
    authorize! :reports, :home
  end



  def multipart_import
    #authorize! :multipart_import, :home
    logger.info("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    logger.info(params)
    logger.info(params[:attachments]["0"])
    logger.info(params[:envelope]["from"])
    logger.info("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    puts "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
    puts params
    puts params[:attachments]["0"]
    puts params[:envelope]["from"]
    puts "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
    email = params[:envelope]["from"]
    admin = Admin.where(:email => email).first rescue nil
    id = admin.id rescue nil

    text, status = if admin
      if params[:attachments]["0"]
        parameters = {file: params[:attachments]["0"], admin_id: id}
        excel_file = ExcelFile.new(parameters)

        ActiveRecord::Base.transaction do
          if excel_file.save
            UserMailer.data_upload_success(admin, excel_file).deliver_later
            ["Success to import data", 200]
            puts "Success to import data"
          else
            #logger.info("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS")
            #logger.info(excel_file.errors.count)
            #logger.info(excel_file.errors.full_messages)
            #logger.info("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS")
            UserMailer.data_upload_failure(admin, excel_file).deliver_later
            ["Failed, We have an error on the import data", 200]
            puts "Failed, We have an error on the import data"
          end
        end
      else
        UserMailer.data_upload_failure_no_attachment(admin).deliver_later
        ["Failed, there is no attached file", 200]
        puts "Failed, there is no attached file"
      end
    else
      UserMailer.data_upload_failure_email_not_recognized(email).deliver_later
      ["Failed, unregistered email not allowed to import", 200]
      puts "Failed, unregistered email not allowed to import"
    end

    logger.info(text)

    render :text => text, :status => status
  end

  def upload_data
    render_upload_data
  end

  def process_upload_data
    parameters = {file: params[:file], admin_id: @currently_signed_in.id}
    @model = ExcelFile.new(parameters)

    if @model.save
      flash[:success] = "Successfully upload data to database"
      redirect_to home_upload_data_url
    else
      flash[:danger] = "Failed to upload data"# + @model.errors.messages[:base].join(". ")
      render_upload_data
    end
  end

  def import_mail
    # message = Mail.new(params[:message])
    # user_id = User.where(:email => message.from.first).first.id rescue nil
    # logger.info(message.from.first)
    # logger.info("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")
    # logger.info(user_id)
    # logger.info(User.where(:email => message.from.first))
    # logger.info(User.pluck(:email))
    # logger.info("-------------------------------")
    # text, status = if user_id
    #   logger.info("TEST EUY TEST TEST TEST")
    #   file = eval(message.attachments.first.read)
    #   Survey.import_from_email(@surveys, user_id)
    #   Landing.import_from_email(@fleets, user_id)
    #   Catch.import_from_email(@catches, user_id)
    #   logger.info("--------------------")

    #   ["success", 200]
    # else
    #   ["failed import data from email -- not registered user email", 200]
    # end

    # render :text => text, :status => status
  end

  #Landing

  def import_mail2
    message = Mail.new(params[:message])
    logger.info("===============================================================")
    logger.info(message.subject) #print the subject to the logs
    logger.info("body decode :" + message.body.decoded) #print the decoded body to the logs
    logger.info("inspect attachment pertama :"+message.attachments.first.inspect) #inspect the first attachment
    logger.info(message.from.first)
    logger.info(message.methods.sort)
    logger.info(message.attachments.first.attachment?)
    logger.info(message.attachments.first.has_attachments?)
    logger.info(message.attachments.first.decode_body)
    logger.info(message.attachments.first.read)
    logger.info("class name : #{message.attachments.first.read.class}")
    logger.info("===============================================================")
    email = User.where(:email => message.from.first)
    text, status = if !email.blank? and message.attachment?
      attached = message.attachments.first.content_disposition.split('.').last
      if attached.eql?('xls') or attached.eql?('xlsx')
        filename = begin message.attachments.first.original_filename
        rescue
          begin
            message.attachments.first.filename
          rescue
            "Database_#{Digest::SHA1.hexdigest("--#{Time.now.to_s}--")[0,6]}.#{attached}"
          end
        end

        logger.info("testing... lihat aku woyyy "+message.attachments.first.content_transfer_encoding.to_s)
        attach_code = message.attachments.first.decoded
        File.open(Rails.root+"/tmp/"+filename, "w") { |file| file.write(attach_code) }
        file = Rails.root+"/tmp/"+filename
        excel_info = File.open(file)
        parameters = {file: excel_info, user_id: email.id}
        excel_file = ExcelFile.new(parameters)
        logger.info(excel_file)

        if excel_file.save
          excel_info.close
          logger.info("import by email : Successfully upload data to database")
          UserMailer.data_upload_success(@currently_signed_in, @model).deliver_later
          ["success", 200]
        else
          excel_info.close
          logger.info(attach_code)
          logger.info(excel_file.errors)
          logger.info("import by email : Failed to upload data")
          UserMailer.data_upload_failure(@currently_signed_in, @model).deliver_later
          ["Failed import data by email", 200]
        end
      else
        logger.info("There is no excel file on the email")
        ["Failed, There is no excel file on the email", 200]
      end
    elsif email.blank?
      logger.info("import by email : Failed to upload data")
      ["The email address not registered on our app.", 200]
    else
      logger.info("There is no attached file on the email")
      ["Failed, There is no attached file on the email", 200]
    end

    render :text => text, :status => status
  end

  def user_profile
  end

  def fishery_profile
  end

private

  def render_upload_data
    @files = ExcelFile.all
    render :action => "upload_data"
  end

  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/home/#{params[:page]}.html.erb"))
  end

  def initialize_select_company_page
    @companies = Company.accessible_by(current_ability).default
  end

  def initialize_select_vessel_page
    @vessels = Vessel.accessible_by(current_ability).default
    @label = params[:label] || nil
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home.html.erb
<div class="row">
	<div class="well well-large">
		<div class="media">
			<%= link_to survey.admin, class: "pull-left" do %>
				<%= image_tag survey.admin.avatar_url(:thumb), width: "50px", height: "50px", class:"media-object" if survey.admin.avatar? %>
			<% end %>
			<div class="media-body">
				<%= link_to survey.admin.name, survey.admin %> did a survey in <%= link_to survey.desa.name, survey.desa %> for the <%= link_to survey.fishery.name, survey.fishery %> fishery.
			</div>
		</div>				
	</div>
</div>

app/views/home/_pagination.html.erb
<ul class="pagination center-block">
	<li id="pagination_previous">
		<%= link_to_previous_page @activities, '<< Previous', remote: true %>
	</li>
	<li id="pagination_next">
		<%= link_to_next_page @activities, 'Next >>', remote: true %>
	</li>
</ul>

app/views/home/fishery_profile.html.erb
TO DO

app/views/home/import.html.erb
<% title "Import Data" %>

<div class='row'>
	<div class='col-xs-12 col-sm-6 col-sm-offset-3'>
		<%= link_to 'Import Unloadings', page_path( page: 'select_vessel', label: 'unloadings'), class: 'btn btn-default btn-block btn-lg' %>
		<%= link_to 'Import Bait Loadings', page_path( page: 'select_vessel', label: 'bait_loadings'), class: 'btn btn-default btn-block btn-lg' %>
    <%= link_to 'Import Vessels',page_path(page: 'select_company'), class: 'btn btn-default btn-block btn-lg' %>
	</div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-push-8">
      <% if admin_signed_in? %>
        <br />
        <br />
        <br />
        <br />
        <div id="quick_links" class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Quick Links</h3>
          </div>
          <div class="panel-body">
            <dl>
              <dt>My fisheries</dt>
              <% for fishery in current_admin.member_fisheries %>
                <dd><%= link_to fishery.name, fishery %></dd>
              <% end %>
            </dl>
          </div>
        </div>
      <% end %>
    </div>
    <div id="recent_activity" class="col-xs-12 col-md-8 col-md-pull-4">
      <div class="page-header text-center">
          <h3 id="timeline">Recent Activity</h3>
      </div>


      <ul class='timeline'>

        <%= render @activities %>

        <li class="clearfix" style="float: none;"></li>
      </ul>


      <div class="row">
        <div class="col-xs-12">
          <%= render partial: 'home/pagination' %>

        </div>

      </div>
    </div>


  </div>
</div>

app/views/home/index.js.erb
$('.timeline').append('<%= j render partial: "activities/activity", collection: @activities, locals: { view: self }  %>');
<% if @activities.last_page? %>
  $('.pagination').remove();
<% else %>
  $('.pagination').replaceWith('<%= j render "pagination" %>');
<% end %>

app/views/home/reports.html.erb
<% title t("navbar.reports") %>

<div class="row">
	<%= link_to provinces_path, class: "col-xs-12 col-md-4 btn btn-warning btn-lg"  do%>
		
			<%= t("provinces.title") %>
	
	<% end %>
	<%= link_to districts_path, class: "col-xs-12 col-md-4 btn btn-warning btn-lg"   do%>
		
			<%= t("districts.title") %>
		
	<% end %>
	<%= link_to desas_path, class: "col-xs-12 col-md-4 btn btn-warning btn-lg"   do%>
		
			<%= t("desas.title") %>
		
	<% end %>
</div>

<br />
<br />

<div class="row">
	<%= link_to fisheries_path, class: "col-xs-12 col-md-4 btn btn-info btn-lg"   do%>
	
			<%= t("fisheries.title") %>

	<% end %>
	<%= link_to fishes_path, class: "col-xs-12 col-md-4 btn btn-info btn-lg"   do%>
	
			<%= t("fishes.title") %>

	<% end %>
	<%= link_to gears_path, class: "col-xs-12 col-md-4 btn btn-info btn-lg"   do%>
		
			<%= t("gears.title") %>
	
	<% end %>
</div>

<br />
<br />

<div class="row">
	<%= link_to users_path, class: "col-xs-12 col-md-4 btn btn-success btn-lg"   do%>
	
			<%= t("users.title") %>

	<% end %>
	<%= link_to admins_path, class: "col-xs-12 col-md-4 col-md-offset-4 btn btn-success btn-lg"   do%>
	
			<%= t("admins.title") %>
	<% end %>


</div>

<br />
<br />

app/views/home/select_company.html.erb
<% title 'Select Company' %>
<div class='row'>
  <div class='col-xs-12 col-sm-8 col-sm-offset-2'>
    <p class='lead'>
      Which Company do you want to import vessels for?
    </p>
  </div>
</div>

<div class='row'>
  <div class='col-xs-12 col-sm-8 col-sm-offset-2'>
    <table class='table table-condensed datatable'>
      <thead>

        <th><%= Company.human_attribute_name(:code) %></th>
        <th><%= Company.human_attribute_name(:name) %></th>
        <th class='nosort'></th>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.code %></td>
            <td><%= company.name %></td>
            <td><%= link_to 'Import', new_company_importer_path(company, label: 'vessels'), class: 'btn btn-default btn-xs', title: "Import to #{company.code}" %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/home/select_vessel.html.erb
<% title 'Select Vessel' %>
<div class='row'>
  <div class='col-xs-12 col-sm-8 col-sm-offset-2'>
    <% if @label == 'bait_loadings' %>
      <p class='lead'>Which Vessel do you want to import Bait Loadings for?</p>
    <% end %>
    <% if @label == 'unloadings' %>
      <p class='lead'>Which Vessel do you want to import Unloadings for?</p>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='col-xs-12 col-sm-8 col-sm-offset-2'>
    <table class='table table-condensed datatable'>
      <thead>

        <th><%= Vessel.human_attribute_name(:ap2hi_ref) %></th>
        <th><%= Vessel.human_attribute_name(:name) %></th>
        <th><%= Vessel.human_attribute_name(:company_id) %></th>
        <th class='nosort'></th>
      </thead>
      <tbody>
        <% @vessels.each do |vessel| %>
          <tr>
            <td><%= vessel.ap2hi_ref %></td>
            <td><%= vessel.name %></td>
            <td><%= vessel.company.try(:name) %></td>
            <td><%= link_to 'Import', new_vessel_importer_path(vessel, label: @label), class: 'btn btn-default btn-xs', title: "Import to #{vessel.ap2hi_ref}" %></td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/home/upload_data.html.erb
<% title "Import Data" %>

<div class="well row">
  <div class="col-xs-12 col-md-6">
    <%= form_tag home_process_upload_data_path, :class => "form-inline", multipart: true do %>
      <div class="form-group">
        <%= file_field_tag "file" %>
      </div>
      <div class="form-group">
        <%= content_tag :button, type: :submit, class: 'btn btn-primary' do %>
          <%= upload_icon %>
          Upload
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-3 col-md-offset-3">
    <div class="row">
      <%= link_to "mailto:#{MAILER_ADDRESS}", class: "btn btn-info col-xs-12" do %>
        <%= email_icon %>
        Submit via email
      <% end %>
    </div>
    <div class="row">

      <%= link_to "/addresscard.vcf", class: "btn btn-default col-xs-12" do %>
        <%= addressbook_icon %>
        Add to Addressbook
      <% end %>
    </div>
  </div>
  
</div>


<div class="row">
  <table class="table table-striped table-condensed">
    <tr>
      <th>Filename</th>
      <th>Filesize</th>
    </tr>

    <% @files.each do |file| %>
      <tr>
        <td><%= link_to file.filename, file %></td>
        <td><%= file.filesize %></td>
      </tr>
    <% end %>
  </table>
</div>

<br />

app/views/home/user_profile.html.erb
TO DO