config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  use_doorkeeper
  mount_griddler

  concern :acts_as_chartable do
    namespace :charts do
      resources :productions, only: :index
      resources :cpues, only: :index
      resources :fuel_utilizations, only: :index
      resources :catch_compositions, only: :index
      resources :bait_efficiencies, only: :index
    end
  end



  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do




    devise_for :users,
      path_prefix: 'session',
      controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    devise_for :admins,
      path_prefix: 'session',
      controllers: {
        registrations: 'admins/registrations',
        sessions: 'admins/sessions',
        passwords: 'admins/passwords'
      },
      path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'account',
        sign_up: 'signup'
      }

    namespace :panel do
      resources :users do
        member do
          post :add_role
          delete :delete_role
        end
      end
      resources :admins do
        member do
          post :add_role
          delete :delete_role
          put :set_approved
        end
      end
      resources :roles, :only=>[:index, :create, :destroy]
    end

    namespace :supervisor do
      resources :surveys
      resources :logbooks
      resources :admins
      resources :dashboard
    end

    namespace :staff do
      resources :dashboard
    end

    resources :catches
    resources :desas do
      resources :surveys
    end
    resources :fisheries do
      concerns :acts_as_chartable
      resources :companies, only: [:create, :new]
      resources :gears, only: [:create, :new]
      resources :fishes, only: [:create, :new]
      resources :offices, only: [:create, :new]
      member do
        get :report
        post :add_target_fish
        delete :delete_target_fish
        post :add_bait_fish
        delete :delete_bait_fish
        post :add_used_gear
        delete :delete_used_gear
        post :add_member_company
        post :create_member_company
        get :new_member_company
        delete :delete_member_company
        post :add_member_office
        delete :delete_member_office
      end
    end
    post    "/fisheries/:fishery_id/memberships/gears"     => "memberships/gears#create",  as: "fishery_add_gear"
    delete  "/fisheries/:fishery_id/memberships/gears/:id" => "memberships/gears#destroy", as: "fishery_remove_gear"
    post    "/fisheries/:fishery_id/memberships/vessels"     => "memberships/vessels#create",  as: "fishery_add_vessel"
    delete  "/fisheries/:fishery_id/memberships/vessels/:id" => "memberships/vessels#destroy", as: "fishery_remove_vessel"
    post    "/fisheries/:fishery_id/memberships/fishes"     => "memberships/fishes#create",  as: "fishery_add_fish"
    delete  "/fisheries/:fishery_id/memberships/fishes/:id" => "memberships/fishes#destroy", as: "fishery_remove_fish"
    resources :fishes do
      collection do
        post :import
        get :autocomplete
      end
    end
    resources :gears
    resources :landings
    resources :offices do
      namespace :memberships do
        #resources :admins, only: [:create, :destroy]
      end
      member do
        post :add_admin
        delete :delete_admin
      end
    end
    post "/offices/:office_id/memberships/admins" => "memberships/admins#create", as: "office_add_admin"
    delete "/offices/:office_id/memberships/admins/:id" => "memberships/admins#destroy", as: "office_remove_admin"
    resources :surveys do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :audits, except: [:edit] do
      resources :pending_vessels, only: [:new, :create]
    end
    resources :engines
    resources :ports do
      concerns :acts_as_chartable
    end
    resources :wpps do
      concerns :acts_as_chartable
    end
    resources :graticules
    resources :vessel_types
    resources :districts
    resources :provinces
    resources :logbooks do
      put :approve, on: :member
      put :pend, on: :member
      put :reject, on: :member
    end
    resources :logged_days
    resources :excel_files
    resources :activities

    resources :responders

    resources :tests
    resources :drafts, only: [:update,:destroy]

    resources :vessels do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :audits, except: [:edit]
      collection do
        get :generate_stickers
      end
    end
    resources :pending_vessels do
      member do
        patch :approve
        patch :reject
      end
    end
    resources :vessel_imports do
      collection do
        get :template
      end
    end
    resources :unloading_imports do
      collection do
        get :template
      end
    end
    resources :bait_loading_imports do
      collection do
        get :template
      end
    end

    resources :unloadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :unloading_catches, only: [:create,:update,:destroy]
    resources :carrier_loadings
    resources :size_classes

    resources :companies do
      concerns :acts_as_chartable
      resources :importers, only: [:new,:create]
      resources :unloadings
      resources :bait_loadings
      resources :carrier_loadings
      resources :vessels
      resources :audits, except: [:edit]
      member do
        get 'crop' => 'companies#crop', :as => :crop
        get :report
        post :add_vessel
        delete :delete_vessel
        get 'report'
        get :average_catch_composition
        get :current_catch_composition
        get :current_monthly_production
        get :average_monthly_production
        get :current_monthly_cpue
        get :average_monthly_cpue
        get :current_fuel_utilization
        post :add_user
        delete :delete_user
      end
    end
    post    "/companies/:company_id/memberships/users"     => "memberships/users#create",  as: "company_add_user"
    delete  "/companies/:company_id/memberships/users/:id" => "memberships/users#destroy", as: "company_remove_user"

    resources :bait_loadings do
      member do
        put :approve
        put :pend
        put :reject
      end
    end
    resources :baits

    resources :documents

    resources :protocols

    resources :users, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get 'welcome' => 'users#welcome', :as => :welcome
        get :report
        get :crop
      end
    end
    resources :admins, only: [:index, :show, :edit, :update], constraints: { id: /[0-9]+/ } do
      member do
        get :welcome
        get :crop
      end
    end

    resources :importers, only: [:index]

    namespace :review do
      resources :unloadings,    only: [:update]
      resources :bait_loadings, only: [:update]
    end

    namespace :api, defaults: {format: 'json'} do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
        # resources :users
        # resources :admins
        # resources :logbooks
        # resources :surveys
        resources :fisheries
        # resources :desas, path: :landing_sites
        # resources :districts
        # resources :provinces
        # resources :engines
        # resources :gears
        resources :fishes
        resources :vessels, only: [:index]
        resources :unloadings, only: [:index]
      end
    end




  #  get 'home/index'
#    get 'home/upload_data'
#    get 'home/import'
    get '/reports' => 'home#reports'
    get '/user_profile' => 'home#user_profile'
    get '/fishery_profile' => 'home#fishery_profile'
    get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"


    match '/multipart_import' => 'home#multipart_import', via: [:get, :post]
    post '/import_mail' => 'home#import_mail'

    post 'home/process_upload_data'

    get "/home/*page"  => "home#show",          as: :page

    #authenticate :admin, lambda { |a| a.admin? } do

    #end
    authenticated :admin do
      root :to => "home#index", as: :admin_root
      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :user do
      root to: 'users#home', as: :user_root
    end
    # handles /valid-locale
    get '/:locale' => 'home#index'
    root to: 'home#index'
    # handles /valid-locale/fake-path
    #match '*path', to: redirect { |params, request| "/#{params[:locale]}" }

  end





  # handles /bad-locale|anything/valid-path
  match '/*locale/*path', to: redirect("/#{I18n.default_locale}/%{path}"), via: :get

  # handles /anything|valid-path-but-no-locale
  match '/*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get

  # handles /
  #root to: redirect("/#{I18n.default_locale}")
  match '', to: redirect("/#{I18n.default_locale}"), via: :get



end

app/controllers/api/v1/surveys_controller.rb
module Api
  module V1
    class SurveysController < ApplicationController
      respond_to :json
      
      def index
        @surveys = Survey.where(approved: true)
      end
      
      def show
        @survey = Survey.find(params[:id])
      end
      
      def create
        respond_with Survey.create(survey_params)
      end
      
      def update
        respond_with Survey.update(params[:id], params[:surveys])
      end
      
      def destroy
        respond_with Survey.destroy(params[:id])
      end

      private

      def survey_params
        params.require(:survey).permit( :desa_id, :end_time, :fishery_id, :start_time, :admin_id, :user_id, :date_published, :observer, :approved,:catch_measurer_id,:catch_scribe_id,:landing_enumerator_id,:vessel_count,:review_state,:reviewed_at,:reviewer,:start_time_input,:end_time_input)
      end
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  load_and_authorize_resource

  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  respond_to :html
  respond_to :xml, :json, :csv, :xls, :js, :except => [ :edit, :new, :update, :create ]

  def index
    @surveys = Survey.all
    respond_with(@surveys)
  end

  def show
    respond_with(@survey)
  end

  def new
    @survey = Survey.new
    respond_with(@survey)
  end

  def edit
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.admin_id = @currently_signed_in.id
    track_activity @survey if @survey.save
    respond_with @survey, location: -> { after_save_path_for(@survey) }
  end

  def update
    @survey.update(survey_params)
    # respond_with @survey, location: -> { after_save_path_for(@survey) }
    respond_to do |format|
      if @survey.update_attributes(survey_params)
        flash[:success] = "Survey updated successfully!"
        format.html { redirect_to(@survey, :notice => 'Survey was successfully updated.') }
        format.json { respond_with_bip(@survey) }
      else
        flash[:error] = @survey.errors.full_messages.join(", ")
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@survey) }
      end
    end
  end

  def destroy
    @survey.destroy
    respond_with(@survey)
  end

  def approve
    @survey = Survey.find( params[:id] )
    @survey.approved!
    if @survey.approved?
      track_activity @survey
      @survey.update_column :reviewer_id, current_admin.id
      flash[:success] = review_success_msg("approved")
    else
      flash[:error] = review_error_msg
    end
    refresh_supervisor_controls( @survey )
  end

  def reject
    @survey = Survey.find( params[:id] )
    @survey.rejected!
    if @survey.rejected?
      track_activity @survey
      @survey.update_column :reviewer_id, current_admin.id
      flash[:success] = review_success_msg("Rejected")
    else
      flash[:error] = review_error_msg
    end
    refresh_supervisor_controls( @survey )
  end

  def pend
    @survey = Survey.find( params[:id] )
    @survey.pending!
    if @survey.pending?
      track_activity @survey
      @survey.update_column :reviewer_id, current_admin.id
      flash[:success] = review_success_msg("Pending")
    else
      flash[:error] = review_error_msg
    end
    refresh_supervisor_controls( @survey )
  end

  private
  
  def set_survey
    @survey = Survey.find(params[:id])
  end

  def survey_params
    params.require(:survey).permit(
      :desa_id, 
      :end_time, 
      :fishery_id, 
      :start_time, 
      :admin_id, 
      :user_id, 
      :date_published, 
      :observer, 
      :approved,
      :catch_measurer_id,
      :catch_scribe_id,
      :landing_enumerator_id,
      :vessel_count,
      :review_state,
      :reviewed_at,
      :reviewer,
      :start_time_input,
      :end_time_input
      )
  end

  def after_save_path_for(resource)
    survey_path(resource)
  end

  def refresh_supervisor_controls( survey )
    respond_to do |format|
      format.html { redirect_to survey  }
      format.js {
        @survey = survey 
        render :refresh_supervisor_controls
      }
    end
  end

  def review_success_msg( state )
    "Survey successfully reviewed: #{state.upcase}"
  end

  def review_error_msg
    "We encountered an error reviewing this survey. Please try again."
  end

end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date_published %>
  </div>
    <%= f.hidden_field :user_id %>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= "Desa" %><br />
    <%= f.select :desa_id, options_for_select(Desa.all.collect {|d|[d.name, d.id]}) %>
  </div>
  <div class="field">
    <%= f.label :fleet_observer %><br />
    <%= f.text_field :fleet_observer %>
  </div>
  <div class="field">
    <%= f.label :catch_measure %><br />
    <%= f.text_field :catch_measure %>
  </div>
  <div class="field">
    <%= f.label :catch_scribe %><br />
    <%= f.text_field :catch_scribe %>
  </div>
  <div class="field">
    <%= "Fishery" %><br />
    <%= f.select :fishery_id, options_for_select(Fishery.all.collect {|d|[d.name, d.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_supervisor_controls.html.erb
<% if can? :update, @survey %>
  <div class="row">
    <div class="col-xs-4">
      <%= link_to :back  do %>
        <%= icon 'arrow-left', "Back" %>
      <% end %>
    </div>
    <div class="col-xs-6 col-xs-offset-2">
      <div class="row">
        <%= link_to reject_survey_path(@survey),
          class: "col-xs-4 btn btn-lg #{@survey.rejected? ? 'btn-danger' : 'btn-default' }",
          method: :put,
          remote: true do
          %>
            <%= icon 'remove', "", class: 'fa-lg' %>
            Rejected
        <% end %>
        <%= link_to pend_survey_path(@survey),
          class: "col-xs-4 btn btn-lg #{@survey.pending? ? 'btn-warning' : 'btn-default' }",
          method: :put,
          remote: true do
          %>
          <%= icon 'warning', "", class: 'fa-lg' %>
          Pending
        <% end %>
        <%= link_to approve_survey_path(@survey),
          class: "col-xs-4 btn btn-lg #{@survey.approved? ? 'btn-success' : 'btn-default' }",
          method: :put,
          remote: true do
          %>
          <%= icon 'check', "", class: 'fa-lg' %>
          Approved
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/surveys/_survey.html.erb
<div class="row">
	<div class="well well-large">
		<div class="media">
			<%= link_to survey.admin, class: "pull-left" do %>
				<%= image_tag survey.admin.avatar_url(:thumb), width: "50px", height: "50px", class:"media-object" if survey.admin.avatar? %>
			<% end %>
			<div class="media-body">
				<%= link_to survey.admin.name, survey.admin %> did a survey in <%= link_to survey.desa.name, survey.desa %> for the <%= link_to survey.fishery.name, survey.fishery %> fishery.
			</div>
		</div>				
	</div>
</div>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<% title t ".title" %>

<div class="row">
  <div class="span8">
    <%= link_to :back do %>
      <i class='icon-arrow-left'></i> Back
    <% end %>
  </div>
  <div class="span4">
    <%= render partial: "shared/api_links", locals: {json: true, xml: true} %>
  </div>

</div>

<br />
<br />


<table class="table table-striped table-condensed">
  <tr>
    <th></th>
    <th><%= Survey.human_attribute_name(:date_published) %></th>
    <th><%= Survey.human_attribute_name(:start_time) %></th>
    <th><%= Survey.human_attribute_name(:end_time) %></th>
    <th><%= Survey.human_attribute_name(:fishery_id) %></th>
    <th><%= Survey.human_attribute_name(:desa_id) %></th>
    <th>Eumerators</th>
    <th><%= Survey.human_attribute_name(:admin_id) %></th>
    <th></th>
  </tr>

  <% @surveys.each do |survey| %>
    <% if survey.approved? %>
      <tr  >
    <% elsif survey.rejected? %>
      <tr class='error' >
    <% elsif survey.pending? %>
      <tr class='warning' >
    <% end %>
      <td>
        <% if survey.approved? %>
          <span class="label label-success"><i class='icon-ok-sign'></i></span>
        <% elsif survey.rejected? %>
          <span class="label label-important"><i class='icon-remove-sign'></i></span>
        <% elsif survey.pending? %>
          <span class="label label-warning"><i class='icon-warning-sign'></i></span>
        <% end %>
      </td>
      <td><%= survey.date_published.to_s(:rfc822) rescue '' %></td>
      <td><%= survey.start_time.to_s(:time) %></td>
      <td><%= survey.end_time.to_s(:time) %></td>
      <td><%= survey.fishery.name rescue ''%></td>
      <td><%= survey.desa.name rescue '' %></td>
      <td>
        <%= link_to image_tag(survey.landing_enumerator.avatar_url(:thumb), 
          width: "30px", 
          height: "30px", 
          title: survey.landing_enumerator.name, 
          alt: survey.landing_enumerator.name),
          survey.landing_enumerator %>
        <%= link_to image_tag(survey.catch_measurer.avatar_url(:thumb), 
          width: "30px", 
          height: "30px", 
          title: survey.catch_measurer.name, 
          alt: survey.catch_measurer.name),
          survey.catch_measurer %>
        <%= link_to image_tag(survey.catch_scribe.avatar_url(:thumb), 
          width: "30px", 
          height: "30px", 
          title: survey.catch_scribe.name, 
          alt: survey.catch_scribe.name),
          survey.catch_scribe %>
      </td>
      <td><%= link_to image_tag(survey.admin.avatar_url(:thumb), 
          width: "30px", 
          height: "30px", 
          title: survey.admin.name, 
          alt: survey.admin.name),
          survey.admin %>
      </td>   
      <td>
        <%= link_to show_icon, survey %>
        <%= link_to edit_icon, edit_survey_path(survey) %>
        <%= link_to destroy_icon, survey, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<br />

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<% title t ".title" %>

<div class="row">
  <div id="supervisor_controls" class= "col-xs-8">
    <%= render partial: "surveys/supervisor_controls" %>
  </div>
  <div class="col-xs-4">
    <%= render partial: "shared/api_links", locals: {json: true, xml: true} %>
  </div>

</div>

<br />
<br />

<% present @survey do |survey_presenter| %> 

  <div class="row">
    <div class="col-xs-12 col-md-4 panel panel-default">
      <div class="panel-heading">Location</div>
      <div class="panel-body">

        <dl class="dl-horizontal">
          
          <dt><%= Survey.human_attribute_name(:fishery_id) %></dt>
          <dd><%= survey_presenter.fishery %></dd>

          <dt><%= Survey.human_attribute_name(:desa_id) %></dt>
          <dd><%= survey_presenter.desa %></dd>

          <dt><%= Desa.human_attribute_name(:district_id) %></dt>
          <dd><%= @survey.district.name rescue '--' %></dd>

          <dt><%= Province.human_attribute_name(:name) %></dt>
          <dd><%= @survey.province.name rescue '--' %></dd>
          
        </dl>
      </div>

    </div>

    <div class="col-xs-12 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">Time</div>
        <div class="panel-body">
          <dl class="dl-horizontal">

            <dt><%= Survey.human_attribute_name(:date_published) %></dt>
            <dd><%= survey_presenter.date %></dd>

            <dt><%= Survey.human_attribute_name(:start_time) %></dt>
            <dd><%= survey_presenter.start_time %></dd>


            <dt><%= Survey.human_attribute_name(:end_time) %></dt>
            <dd><%= survey_presenter.end_time %></dd>

          </dl>
        </div>
      </div>

    </div>

    <div class="col-xs-12 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">Survey team</div>
        <div class="panel-body">
          <dl class="dl-horizontal">

            
            <dt><%= Survey.human_attribute_name(:admin_id) %></dt>
            <dd><%= survey_presenter.admin %></dd>

            
            <dt><%= Survey.human_attribute_name(:fleet_observer) %></dt>
            <dd><%= survey_presenter.landing_enumerator %></dd>


            <dt><%= Survey.human_attribute_name(:catch_measure) %></dt>
            <dd><%= survey_presenter.catch_measurer %></dd>


            <dt><%= Survey.human_attribute_name(:catch_scribe) %></dt>
            <dd><%= survey_presenter.catch_scribe %></dd>

          </dl>
        </div>
      </div>

    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-12 col-md-4">
    <div class="panel panel-default">

      <table class="table table-striped table-condensed">
        <tr>
          <th><%= Landing.human_attribute_name(:vessel_ref) %></th>
          <th><%= Landing.human_attribute_name(:vessel_name) %></th>
          <th><%= Landing.human_attribute_name(:grid_square) %></th>
          <th><%= Landing.human_attribute_name(:vessel_type_id) %></th>
          <th><%= Landing.human_attribute_name(:time_out) %></th>
          <th><%= Landing.human_attribute_name(:time_in) %></th>
          <th><%= Landing.human_attribute_name(:engine) %></th>
          <th><%= Landing.human_attribute_name(:fuel) %></th>
          <th><%= Landing.human_attribute_name(:sail) %></th>
          <th><%= Landing.human_attribute_name(:crew) %></th>
          <th><%= Landing.human_attribute_name(:boat_size) %></th>
          <th><%= Landing.human_attribute_name(:gear_id) %></th>
          <th><%= Landing.human_attribute_name(:quantity) %></th>
          <th><%= Landing.human_attribute_name(:weight) %></th>
          <th><%= Landing.human_attribute_name(:value) %></th>
          <th></th>
        </tr>

        <% for landing in @survey.landings %>
          <% present landing do |landing_presenter| %> 
            <tr>
              <td><%= landing_presenter.vessel_ref %></td>
              <td><%= landing_presenter.vessel_name %></td>
              <td><%= landing_presenter.graticule %></td>
              <td><%= landing_presenter.vessel_type %></td>
              <td><%= landing_presenter.time_out %></td>
              <td><%= landing_presenter.time_in %></td>
              <td><%= landing_presenter.engine %></td>
              <td><%= landing_presenter.fuel %></td>
              <td><%= landing_presenter.sail %></td>
              <td><%= landing_presenter.crew %></td>
              <td><%= landing_presenter.boat_size %></td>
              <td><%= landing_presenter.gear %></td>
              <td><%= landing_presenter.quantity %></td>
              <td><%= landing_presenter.weight %></td>
              <td><%= landing_presenter.value %></td>
              <td>
                <%= link_to show_icon, landing %>
                <%= link_to edit_icon, landing %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>


<%= render partial: 'shared/audit_table', locals: { parent: @survey } %>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>